### ISSUE TITLE
缺少依赖

### ISSUE THREAD

**Issue by Ssunhx** [JoneXiong/oejia_menu#4]
你好：
       非常感谢你能分享odoo的主题，我安装使用了你的模块，但是安装的时候报出了缺少依赖的包的错误，"The ID "oejia_menu.menu" refers to an uninstalled module"，出错的位置是在
oejia_menu.menu这个id下的一段
你知道我是缺少那个模块吗？
ps：我的版本是odoo12，社区版，使用的也是你的12分支的模块

**Comment by Ssunhx** [comment]
代码没贴上，错误是在这报出的
`<t t-name="oejia_menu.menu">
        <ul class="nav navbar-nav navbar-left oe_application_menu_placeholder" style="display: none;">
            <li t-foreach="menu_data['children']" t-as="menu">
                <t t-call="oejia_menu.menu_link"/>
            </li>
            <li id="menu_more_container" class="dropdown" style="display: none;">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"/></a>
                <ul id="menu_more" class="dropdown-menu"/>
            </li>
        </ul>

    </t>`

**Comment by JoneXiong** [comment]
@Ssunhx 请确认模块目录名是否为oejia_menu 不能随便改的 比如 -12  -master 之类的后缀不要带

**Comment by gyx465279680** [comment]
您好： 我安装报错

报错信息：Odoo Server Error
Traceback (most recent call last):
File "/home/gong/odoo/odoo/tools/cache.py", line 88, in lookup
r = d[key]
File "/home/gong/odoo/odoo/tools/func.py", line 69, in wrapper
return func(self, *args, **kwargs)
File "/home/gong/odoo/odoo/tools/lru.py", line 44, in getitem
a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f3412f617b8>, 'web.menu_secondary_submenu')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/gong/odoo/odoo/tools/convert.py", line 757, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/home/gong/odoo/odoo/tools/convert.py", line 735, in _tag_template
return self._tag_record(record, data_node)
File "/home/gong/odoo/odoo/tools/convert.py", line 649, in _tag_record
f_val = self.id_get(f_ref)
File "/home/gong/odoo/odoo/tools/convert.py", line 740, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/home/gong/odoo/odoo/tools/convert.py", line 746, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/home/gong/odoo/odoo/addons/base/models/ir_model.py", line 1380, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/home/gong/odoo/odoo/tools/cache.py", line 93, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/home/gong/odoo/odoo/addons/base/models/ir_model.py", line 1369, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.menu_secondary_submenu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/gong/odoo/odoo/http.py", line 654, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/gong/odoo/odoo/http.py", line 312, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/home/gong/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/home/gong/odoo/odoo/http.py", line 696, in dispatch
result = self._call_function(**self.params)
File "/home/gong/odoo/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/gong/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/home/gong/odoo/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/home/gong/odoo/odoo/http.py", line 939, in call
return self.method(*args, **kw)
File "/home/gong/odoo/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/home/gong/odoo/addons/web/controllers/main.py", line 967, in call_button
action = self._call_kw(model, method, args, {})
File "/home/gong/odoo/addons/web/controllers/main.py", line 955, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/home/gong/odoo/odoo/api.py", line 749, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/home/gong/odoo/odoo/api.py", line 736, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "", line 2, in button_immediate_install
File "/home/gong/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
return method(self, *args, **kwargs)
File "/home/gong/odoo/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
return self._button_immediate_function(type(self).button_install)
File "/home/gong/odoo/odoo/addons/base/models/ir_module.py", line 552, in _button_immediate_function
modules.registry.Registry.new(self._cr.dbname, update_module=True)
File "/home/gong/odoo/odoo/modules/registry.py", line 86, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/gong/odoo/odoo/modules/loading.py", line 421, in load_modules
loaded_modules, update_module, models_to_check)
File "/home/gong/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/home/gong/odoo/odoo/modules/loading.py", line 222, in load_module_graph
load_data(cr, idref, mode, kind='data', package=package, report=report)
File "/home/gong/odoo/odoo/modules/loading.py", line 68, in load_data
tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
File "/home/gong/odoo/odoo/tools/convert.py", line 801, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/home/gong/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/home/gong/odoo/odoo/tools/convert.py", line 763, in parse
exc_info[2]
File "/home/gong/odoo/odoo/tools/pycompat.py", line 86, in reraise
raise value.with_traceback(tb)
File "/home/gong/odoo/odoo/tools/convert.py", line 757, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/home/gong/odoo/odoo/tools/convert.py", line 735, in _tag_template
return self._tag_record(record, data_node)
File "/home/gong/odoo/odoo/tools/convert.py", line 649, in _tag_record
f_val = self.id_get(f_ref)
File "/home/gong/odoo/odoo/tools/convert.py", line 740, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/home/gong/odoo/odoo/tools/convert.py", line 746, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/home/gong/odoo/odoo/addons/base/models/ir_model.py", line 1380, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/home/gong/odoo/odoo/tools/cache.py", line 93, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/home/gong/odoo/odoo/addons/base/models/ir_model.py", line 1369, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: web.menu_secondary_submenu" while parsing None:3, near


oe_secondary_submenu nav nav-pills nav-stacked hide_secondary

**Comment by gyx465279680** [comment]
您好：odoo12 版本安装报错，麻烦您帮忙解决一下。
报错信息：
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.
Could not execute command 'lessc'This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /oejia_menu/static/src/less/variables.less
    - /oejia_menu/static/src/less/navbar.less
    - /oejia_menu/static/src/less/style.less
    - /web_settings_dashboard/static/src/scss/dashboard.scss
Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.
